apiVersion: v1
kind: Service
metadata:
  labels:
    app: karsajobs
  name: karsajobs
  namespace: submission
spec:
  type: NodePort  # Untuk mengubah tipe layanan jadi NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30009  # Untuk menentukan port NodePort yang dipidahkan pada node
  selector:
    app: karsajobs