apiVersion: v1
kind: Service
metadata:
  labels:
    app: karsajobs-ui
  name: karsajobs-ui
  namespace: submission
spec:
  type: NodePort  # Untuk mengubah tipe layanan jadi NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30019  # Untuk menentukan port NodePort yang dipindahkan pada node
  selector:
    app: karsajobs-ui