apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-volume
  namespace: submission
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Untuk menentukan ukuran penyimpanan
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  namespace: submission
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Untuk menentukan ukuran penyimpanan