apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: submission
  labels:
    app: mongo
spec:
  ports:
    - port: 27017  # Untuk port standart mongoDB
  selector:
    app: mongo
    tier: backend
  clusterIP: None